language: node_js
node_js:
  - "10.3.0"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $f
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: dev